POST http://localhost:3001/api/productos
Content-Type: application/json

{
    "content": "0123456789",
    "desc": "esta es una prueba de producto",
    "name": "nevera",
    "price": 100,
    "Discount": "30",
    "total_price": 100,
    "categoria": "linea blanca"
}