PUT http://localhost:3001/api/Productos/631d36364be5b65efef895f2
Content-Type: application/json

{
    "content": "0123456789",
    "desc": "esta es una prueba de producto actualizada",
    "name": "nevera",
    "price": 100,
    "Discount": "30",
    "total_price": 100,
    "categoria": "linea blanca"

}